repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - id: check-json
    exclude: devcontainer/devcontainer.json
  - id: check-toml
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
- hooks:
  - args:
    - --fix
    id: ruff-check
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.2
